"""empty message

Revision ID: 4f4a541ec696
Revises: c6b4019c5d35
Create Date: 2025-07-22 19:50:21.631583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f4a541ec696'
down_revision: Union[str, Sequence[str], None] = 'c6b4019c5d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socialnetworks',
    sa.Column('type', sa.String(length=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username_network', sa.String(length=150), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_network')
    )
    op.drop_table('youtube')
    op.drop_table('vk')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vk',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username_network', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('vk_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('vk_pkey')),
    sa.UniqueConstraint('username_network', name=op.f('vk_username_network_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('youtube',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username_network', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('youtube_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('youtube_pkey')),
    sa.UniqueConstraint('username_network', name=op.f('youtube_username_network_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('socialnetworks')
    # ### end Alembic commands ###
