"""empty message

Revision ID: 74b170b3f717
Revises: d900b4609290
Create Date: 2025-07-27 01:44:28.530272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b170b3f717'
down_revision: Union[str, Sequence[str], None] = 'd900b4609290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_title_username', 'socialnetworks', ['title', 'username_network'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_title_username', 'socialnetworks', type_='unique')
    # ### end Alembic commands ###
