"""empty message

Revision ID: 8cf57b76f639
Revises: 77b3a9459e43
Create Date: 2025-07-22 20:42:39.943696

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8cf57b76f639'
down_revision: Union[str, Sequence[str], None] = '77b3a9459e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_type_username', 'socialnetworks', ['type', 'username_network'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_type_username', 'socialnetworks', type_='unique')
    # ### end Alembic commands ###
