"""empty message

Revision ID: 9b23e99c74de
Revises: 7e0807bb035c
Create Date: 2025-07-25 16:41:09.165227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b23e99c74de'
down_revision: Union[str, Sequence[str], None] = '7e0807bb035c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklistaccesstoken', sa.Column('access_token', sa.String(length=400), nullable=False))
    op.drop_constraint(op.f('blacklistaccesstoken_access_toren_key'), 'blacklistaccesstoken', type_='unique')
    op.create_unique_constraint(None, 'blacklistaccesstoken', ['access_token'])
    op.drop_column('blacklistaccesstoken', 'access_toren')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklistaccesstoken', sa.Column('access_toren', sa.VARCHAR(length=400), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'blacklistaccesstoken', type_='unique')
    op.create_unique_constraint(op.f('blacklistaccesstoken_access_toren_key'), 'blacklistaccesstoken', ['access_toren'], postgresql_nulls_not_distinct=False)
    op.drop_column('blacklistaccesstoken', 'access_token')
    # ### end Alembic commands ###
