"""empty message

Revision ID: d900b4609290
Revises: bc376cffb8bf
Create Date: 2025-07-27 00:33:59.259092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd900b4609290'
down_revision: Union[str, Sequence[str], None] = 'bc376cffb8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersocialnetwork',
    sa.Column('social_network_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['social_network_id'], ['socialnetworks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('socialnetworks', sa.Column('title', sa.String(length=7), nullable=False))
    op.drop_constraint(op.f('uq_type_username'), 'socialnetworks', type_='unique')
    op.drop_constraint(op.f('socialnetworks_user_id_fkey'), 'socialnetworks', type_='foreignkey')
    op.drop_column('socialnetworks', 'type')
    op.drop_column('socialnetworks', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socialnetworks', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('socialnetworks', sa.Column('type', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('socialnetworks_user_id_fkey'), 'socialnetworks', 'users', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_type_username'), 'socialnetworks', ['type', 'username_network'], postgresql_nulls_not_distinct=False)
    op.drop_column('socialnetworks', 'title')
    op.drop_table('usersocialnetwork')
    # ### end Alembic commands ###
