"""empty message

Revision ID: ea761444f490
Revises: 8cf57b76f639
Create Date: 2025-07-22 20:44:20.819261

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea761444f490'
down_revision: Union[str, Sequence[str], None] = '8cf57b76f639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('socialnetworks_username_network_key'), 'socialnetworks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('socialnetworks_username_network_key'), 'socialnetworks', ['username_network'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
